In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split

In [2]:
X_full = pd.read_csv("train.csv", index_col= 'Id')
X_test_full = pd.read_csv("test.csv", index_col = 'Id')

In [3]:
X_full

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1             60       RL         65.0     8450   Pave   NaN      Reg   
2             20       RL         80.0     9600   Pave   NaN      Reg   
3             60       RL         68.0    11250   Pave   NaN      IR1   
4             70       RL         60.0     9550   Pave   NaN      IR1   
5             60       RL         84.0    14260   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1456          60       RL         62.0     7917   Pave   NaN      Reg   
1457          20       RL         85.0    13175   Pave   NaN      Reg   
1458          70       RL         66.0     9042   Pave   NaN      Reg   
1459          20       RL         68.0     9717   Pave   NaN      Reg   
1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... PoolArea PoolQC  Fence MiscFeature  \
Id                                    ...                                      
1            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
2            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
3            Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
4            Lvl    AllPub    Corner  ...        0    NaN    NaN         NaN   
5            Lvl    AllPub       FR2  ...        0    NaN    NaN         NaN   
...          ...       ...       ...  ...      ...    ...    ...         ...   
1456         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1457         Lvl    AllPub    Inside  ...        0    NaN  MnPrv         NaN   
1458         Lvl    AllPub    Inside  ...        0    NaN  GdPrv        Shed   
1459         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   
1460         Lvl    AllPub    Inside  ...        0    NaN    NaN         NaN   

     MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                               
1          0      2    2008        WD         Normal     208500  
2          0      5    2007        WD         Normal     181500  
3          0      9    2008        WD         Normal     223500  
4          0      2    2006        WD        Abnorml     140000  
5          0     12    2008        WD         Normal     250000  
...      ...    ...     ...       ...            ...        ...  
1456       0      8    2007        WD         Normal     175000  
1457       0      2    2010        WD         Normal     210000  
1458    2500      5    2010        WD         Normal     266500  
1459       0      4    2010        WD         Normal     142125  
1460       0      6    2008        WD         Normal     147500  

[1460 rows x 80 columns]

In [4]:
X_test_full

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1461          20       RH         80.0    11622   Pave   NaN      Reg   
1462          20       RL         81.0    14267   Pave   NaN      IR1   
1463          60       RL         74.0    13830   Pave   NaN      IR1   
1464          60       RL         78.0     9978   Pave   NaN      IR1   
1465         120       RL         43.0     5005   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
2915         160       RM         21.0     1936   Pave   NaN      Reg   
2916         160       RM         21.0     1894   Pave   NaN      Reg   
2917          20       RL        160.0    20000   Pave   NaN      Reg   
2918          85       RL         62.0    10441   Pave   NaN      Reg   
2919          60       RL         74.0     9627   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
Id                                    ...                                      
1461         Lvl    AllPub    Inside  ...         120        0    NaN  MnPrv   
1462         Lvl    AllPub    Corner  ...           0        0    NaN    NaN   
1463         Lvl    AllPub    Inside  ...           0        0    NaN  MnPrv   
1464         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1465         HLS    AllPub    Inside  ...         144        0    NaN    NaN   
...          ...       ...       ...  ...         ...      ...    ...    ...   
2915         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
2916         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
2917         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
2918         Lvl    AllPub    Inside  ...           0        0    NaN  MnPrv   
2919         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
Id                                                                 
1461         NaN       0       6    2010        WD         Normal  
1462        Gar2   12500       6    2010        WD         Normal  
1463         NaN       0       3    2010        WD         Normal  
1464         NaN       0       6    2010        WD         Normal  
1465         NaN       0       1    2010        WD         Normal  
...          ...     ...     ...     ...       ...            ...  
2915         NaN       0       6    2006        WD         Normal  
2916         NaN       0       4    2006        WD        Abnorml  
2917         NaN       0       9    2006        WD        Abnorml  
2918        Shed     700       7    2006        WD         Normal  
2919         NaN       0      11    2006        WD         Normal  

[1459 rows x 79 columns]

In [5]:
X_full.shape, X_test_full.shape

((1460, 80), (1459, 79))

In [6]:
X_full.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = X_full.SalePrice
X_full.drop(['SalePrice'], axis=1, inplace=True)

In [7]:
X_full

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                      
1             60       RL         65.0     8450   Pave   NaN      Reg   
2             20       RL         80.0     9600   Pave   NaN      Reg   
3             60       RL         68.0    11250   Pave   NaN      IR1   
4             70       RL         60.0     9550   Pave   NaN      IR1   
5             60       RL         84.0    14260   Pave   NaN      IR1   
...          ...      ...          ...      ...    ...   ...      ...   
1456          60       RL         62.0     7917   Pave   NaN      Reg   
1457          20       RL         85.0    13175   Pave   NaN      Reg   
1458          70       RL         66.0     9042   Pave   NaN      Reg   
1459          20       RL         68.0     9717   Pave   NaN      Reg   
1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities LotConfig  ... ScreenPorch PoolArea PoolQC  Fence  \
Id                                    ...                                      
1            Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
2            Lvl    AllPub       FR2  ...           0        0    NaN    NaN   
3            Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
4            Lvl    AllPub    Corner  ...           0        0    NaN    NaN   
5            Lvl    AllPub       FR2  ...           0        0    NaN    NaN   
...          ...       ...       ...  ...         ...      ...    ...    ...   
1456         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1457         Lvl    AllPub    Inside  ...           0        0    NaN  MnPrv   
1458         Lvl    AllPub    Inside  ...           0        0    NaN  GdPrv   
1459         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   
1460         Lvl    AllPub    Inside  ...           0        0    NaN    NaN   

     MiscFeature MiscVal  MoSold  YrSold  SaleType  SaleCondition  
Id                                                                 
1            NaN       0       2    2008        WD         Normal  
2            NaN       0       5    2007        WD         Normal  
3            NaN       0       9    2008        WD         Normal  
4            NaN       0       2    2006        WD        Abnorml  
5            NaN       0      12    2008        WD         Normal  
...          ...     ...     ...     ...       ...            ...  
1456         NaN       0       8    2007        WD         Normal  
1457         NaN       0       2    2010        WD         Normal  
1458        Shed    2500       5    2010        WD         Normal  
1459         NaN       0       4    2010        WD         Normal  
1460         NaN       0       6    2008        WD         Normal  

[1460 rows x 79 columns]

In [8]:
y

Id
1       208500
2       181500
3       223500
4       140000
5       250000
         ...  
1456    175000
1457    210000
1458    266500
1459    142125
1460    147500
Name: SalePrice, Length: 1460, dtype: int64

In [9]:
X_train_full, X_valid_full, y_train, y_valid = train_test_split(X_full, y, 
                                                                train_size=0.8, test_size=0.2,
                                                                random_state=0)

In [10]:
X_train_full.shape, X_valid_full.shape, y_train.shape, y_valid.shape

((1168, 79), (292, 79), (1168,), (292,))

In [11]:
categorical_cols = [cname for cname in X_train_full.columns if
                    X_train_full[cname].nunique() < 10 and 
                    X_train_full[cname].dtype == "object"]

In [12]:
categorical_cols

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [13]:
numerical_cols = [cname for cname in X_train_full.columns if 
                X_train_full[cname].dtype in ['int64', 'float64']]

In [14]:
numerical_cols

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold']

In [15]:
my_cols = categorical_cols + numerical_cols
X_train = X_train_full[my_cols].copy()
X_valid = X_valid_full[my_cols].copy()
X_test = X_test_full[my_cols].copy()

In [16]:
my_cols

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 '

In [17]:
X_train

MSZoning Street Alley LotShape LandContour Utilities LotConfig LandSlope  \
Id                                                                              
619        RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl   
871        RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl   
93         RL   Pave  Grvl      IR1         HLS    AllPub    Inside       Gtl   
818        RL   Pave   NaN      IR1         Lvl    AllPub   CulDSac       Gtl   
303        RL   Pave   NaN      IR1         Lvl    AllPub    Corner       Gtl   
...       ...    ...   ...      ...         ...       ...       ...       ...   
764        RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl   
836        RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl   
1217       RM   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl   
560        RL   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl   
685        RL   Pave   NaN      IR2         Lvl    AllPub   CulDSac       Gtl   

     Condition1 Condition2  ... GarageArea WoodDeckSF OpenPorchSF  \
Id                          ...                                     
619        Norm       Norm  ...        774          0         108   
871        PosN       Norm  ...        308          0           0   
93         Norm       Norm  ...        432          0           0   
818        Norm       Norm  ...        857        150          59   
303        Norm       Norm  ...        843        468          81   
...         ...        ...  ...        ...        ...         ...   
764        Norm       Norm  ...        856          0         128   
836        Norm       Norm  ...        436        290           0   
1217       RRAe       Norm  ...        539          0           0   
560        Norm       Norm  ...        420        143          20   
685        Norm       Norm  ...        486          0          81   

     EnclosedPorch 3SsnPorch ScreenPorch PoolArea MiscVal MoSold YrSold  
Id                                                                       
619              0         0         260        0       0      7   2007  
871              0         0           0        0       0      8   2009  
93              44         0           0        0       0      8   2009  
818              0         0           0        0       0      7   2008  
303              0         0           0        0       0      1   2006  
...            ...       ...         ...      ...     ...    ...    ...  
764              0         0         180        0       0      7   2009  
836              0         0           0        0       0      2   2010  
1217             0         0           0        0       0      4   2010  
560              0         0           0        0       0     10   2006  
685              0         0           0        0       0      6   2010  

[1168 rows x 76 columns]

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

In [19]:
numerical_transformer = SimpleImputer(strategy='constant')

In [20]:
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

In [21]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

In [22]:
preprocessor

ColumnTransformer(transformers=[('num', SimpleImputer(strategy='constant'),
                                 ['MSSubClass', 'LotFrontage', 'LotArea',
                                  'OverallQual', 'OverallCond', 'YearBuilt',
                                  'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
                                  'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
                                  '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
                                  'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath',
                                  'FullBath', 'HalfBath', 'BedroomAbvGr',
                                  'K...
                                 ['MSZoning', 'Street', 'Alley', 'LotShape',
                                  'LandContour', 'Utilities', 'LotConfig',
                                  'LandSlope', 'Condition1', 'Condition2',
                                  'BldgType', 'HouseStyle', 'RoofStyle',
                                  'RoofMatl', 'MasVn

# Random Forest Regressor

In [23]:
# Define model1
model1 = RandomForestRegressor(n_estimators=800,random_state=20)

# Bundle preprocessing and modeling code in a pipeline
my_pipeline1 = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', model1)
                             ])

# Preprocessing of training data, fit model 
my_pipeline1.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds1 = my_pipeline1.predict(X_valid)

In [37]:
preds1

array([214241.90125, 147757.3775 , 108355.32875, 224123.2325 ,
        89891.23875, 111492.89125, 259471.7325 , 122720.75875,
       515745.43875, 152452.515  , 196670.26375, 146900.7225 ,
       225306.69125, 115129.44375, 126206.8475 , 149421.29625,
       225872.25875, 114917.7675 , 143393.0125 , 195709.53   ,
       127175.67375, 142517.02375, 112171.19625, 168724.67   ,
       182688.28625, 219609.6725 , 168171.3375 ,  84950.7575 ,
       333736.015  , 119775.84875, 134604.36   , 196013.5425 ,
       141756.44   , 287814.30375, 333525.99875, 183844.26   ,
       288953.87125, 125012.12375, 233693.825  , 302936.50625,
       208130.40875, 127237.225  , 179328.145  , 294911.2225 ,
       322461.6075 , 145652.875  , 127704.98625, 128725.25375,
       169116.2325 , 103883.32625, 362292.145  , 145230.5625 ,
       168862.755  ,  88746.15   , 239800.10625, 111317.45625,
       133715.9175 , 242996.495  , 138941.25   , 106310.83625,
       143853.19875, 133010.84375, 144520.61125, 152274

# RandomizedCV

In [24]:

from sklearn.model_selection import RandomizedSearchCV

In [25]:

#Randomized Search CV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1200, num = 12)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 30, num = 6)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10, 15, 100]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 5, 10]

In [26]:

# Create the random grid

random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

In [27]:
rf_random = RandomizedSearchCV(estimator = model1, param_distributions = random_grid,scoring='neg_mean_squared_error', n_iter = 10, cv = 5, verbose=2, random_state=42, n_jobs = 1)

In [28]:
randomized = Pipeline(steps=[('preprocessor', preprocessor),
                              ('random', rf_random)
                             ])

In [29]:
randomized.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.9s
[CV] END max_depth=10, max_features=sqrt, min_samples_leaf=5, min_samples_split=5, n_estimators=900; total time=   0.9s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   1.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimators=1100; total time=   1.2s
[CV] END max_depth=15, max_features=sqrt, min_samples_leaf=2, min_samples_split=10, n_estimator

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  SimpleImputer(strategy='constant'),
                                                  ['MSSubClass', 'LotFrontage',
                                                   'LotArea', 'OverallQual',
                                                   'OverallCond', 'YearBuilt',
                                                   'YearRemodAdd', 'MasVnrArea',
                                                   'BsmtFinSF1', 'BsmtFinSF2',
                                                   'BsmtUnfSF', 'TotalBsmtSF',
                                                   '1stFlrSF', '2ndFlrSF',
                                                   'LowQualFinSF', 'GrLivArea',
                                                   'BsmtFullBath',
                                                   'BsmtHalfBath', 'FullBa...
                                    estimator=Ran

In [30]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 25}

# Model Trained after Randomized CV best Parameters.

In [35]:
# Define model1
tuned_rand = RandomForestRegressor(n_estimators = 1000,
 min_samples_split= 2,
 min_samples_leaf= 1,
 max_features= 'sqrt',
 max_depth= 25)

# Bundle preprocessing and modeling code in a pipeline
my_pipeline2= Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', tuned_rand)
                             ])

# Preprocessing of training data, fit model 
my_pipeline2.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds2= my_pipeline2.predict(X_valid)

In [36]:
preds2

array([239477.642     , 139547.46296032, 129156.87233333, 200971.46171429,
        97966.845     , 107727.49976471, 251115.521     , 132710.66746154,
       478110.165     , 160701.328     , 204180.337     , 149729.475     ,
       230257.021     , 133271.14079798, 127904.23273333, 141955.30380375,
       225855.093     , 117497.01068254, 139599.38885714, 174150.443     ,
       133621.83004487, 146992.107     , 119864.549     , 168895.099     ,
       198133.63135294, 204744.709     , 171707.71766667,  87210.16      ,
       334020.49      , 116344.87486142, 149241.239     , 202029.369     ,
       146873.52728571, 290146.762     , 331019.625     , 187455.553     ,
       277007.279     , 127263.35630141, 229837.198     , 301749.619     ,
       204057.46571429, 139517.60233333, 183007.97346667, 300638.462     ,
       324004.184     , 150847.113     , 130567.59128571, 131887.46519481,
       169023.021     , 113989.87878571, 352379.666     , 146779.57712418,
       169453.15      , 1

# XG boost

In [40]:
from xgboost import XGBRegressor

In [41]:
# Define model1
xgboost = XGBRegressor()

# Bundle preprocessing and modeling code in a pipeline
xgpipe= Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', xgboost)
                             ])

# Preprocessing of training data, fit model 
xgpipe.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds3 = xgpipe.predict(X_valid)

In [42]:
preds3

array([185511.34 , 150436.08 , 113585.55 , 209112.08 , 100093.08 ,
        94251.55 , 260998.53 , 142495.33 , 454737.1  , 160813.08 ,
       192898.08 , 142813.3  , 228010.48 , 118137.78 , 134026.39 ,
       137573.17 , 222845.83 , 124243.85 , 137184.95 , 194560.64 ,
       134162.66 , 146020.19 , 112658.336, 158836.69 , 191278.28 ,
       150238.72 , 175694.58 ,  80848.71 , 316320.1  ,  99656.85 ,
       119682.805, 189352.38 , 143927.56 , 282174.7  , 336860.8  ,
       199234.23 , 297722.7  , 130177.414, 225839.88 , 309187.47 ,
       230213.6  , 130539.05 , 187171.03 , 307898.5  , 279521.97 ,
       145726.7  , 128363.54 , 128571.53 , 174382.98 ,  91783.63 ,
       435068.44 , 148601.25 , 162288.14 ,  72112.7  , 216934.3  ,
        99986.65 , 143416.31 , 256285.67 , 138797.83 , 100058.2  ,
       139619.11 , 133992.83 , 142031.33 , 168174.08 , 221850.02 ,
       166831.67 , 133774.02 , 235565.67 , 125347.93 , 178301.61 ,
       182909.9  , 139991.8  ,  83837.84 , 241735.67 ,  95305.

# Gradient Boosting Regressor

In [65]:
# Define model2
from sklearn.ensemble import GradientBoostingRegressor
grad = GradientBoostingRegressor(n_estimators=600, random_state=32)

# Bundle preprocessing and modeling code in a pipeline
grad_pipe = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', grad)
                             ])

# Preprocessing of training data, fit model 
grad_pipe.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds4 = grad_pipe.predict(X_valid)

In [66]:
preds4

array([206163.47963517, 155814.33523066, 102830.82593049, 201184.42912776,
        88639.75551306,  91506.33730506, 266660.34720952, 122875.06570438,
       649850.92031886, 152207.71309915, 209134.99972641, 147884.77048394,
       247480.19056112, 120845.2011828 , 120530.81510279, 150653.54173882,
       222112.89071337, 124069.796032  , 143319.02919369, 204254.09937862,
       122162.02723733, 146811.37329044, 116765.82780011, 156616.7780388 ,
       186946.13040137, 215524.67362685, 166081.23091503,  77005.39088776,
       331914.85480126, 115900.54317175, 129783.47402199, 185520.31443635,
       145784.75775206, 275576.85195138, 327136.79713869, 193043.51956214,
       310302.72802382, 120510.85827873, 236739.4520831 , 323189.32067698,
       204415.97372252, 119405.23394772, 191909.17235568, 298587.45134886,
       381738.96208349, 136449.01286997, 131394.8112827 , 125875.99561222,
       174373.43960648,  96382.45584552, 406739.70843707, 145733.49333081,
       171130.25691161,  

MAE: 15563.235198675247


# Tuned Gradient Boosting

In [68]:
# Define model2
from sklearn.ensemble import GradientBoostingRegressor
grad_tuned = GradientBoostingRegressor(n_estimators = 1000,
 min_samples_split= 2,
 min_samples_leaf= 1,
 max_features= 'sqrt',
 max_depth= 25)

# Bundle preprocessing and modeling code in a pipeline
grad_pipe1 = Pipeline(steps=[('preprocessor', preprocessor),
                              ('model', grad_tuned)
                             ])

# Preprocessing of training data, fit model 
grad_pipe1.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds5 = grad_pipe1.predict(X_valid)

In [71]:
preds5

array([217177.39960506, 136916.77456627, 142275.80877253, 191840.79081064,
       100404.45696298,  98129.58821468, 244535.9854126 , 135007.38970606,
       494687.05542661, 157674.84143607, 209114.51017771, 165646.8617104 ,
       221229.31184698, 145909.17645658, 132879.29262563, 138008.42877553,
       235611.81885294, 109483.84598514, 155037.89469899, 182319.60901419,
       122066.59458905, 143091.3701    , 135765.40059047, 176843.23640075,
       186726.67164636, 192061.18476726, 174709.33088524,  80798.11995643,
       327005.4083312 , 117843.36899851, 133147.03529669, 201633.52181583,
       142383.68795953, 276622.40490636, 347816.85096392, 188031.94757218,
       274631.07338893, 129096.85225263, 233895.48108274, 302207.14635229,
       200278.91523842, 134319.74633861, 176697.99729773, 311981.33820315,
       335975.87837332, 137369.74981677, 132774.52959063, 134511.29815392,
       164618.36934729, 114801.57888927, 385103.40320379, 148429.59085106,
       155520.52433291,  

MAE: 18569.139198068155


In [73]:
score = mean_absolute_error(y_valid, preds1)
print('1 - MAE:', score)
score = mean_absolute_error(y_valid, preds2)
print('2 - MAE:', score)
score = mean_absolute_error(y_valid, preds3)
print('3 - MAE:', score)
score = mean_absolute_error(y_valid, preds4)
print('4 - MAE:', score)
score = mean_absolute_error(y_valid, preds5)
print('5 - MAE:', score)


1 - MAE: 17226.008848458903
2 - MAE: 17822.73354201734
3 - MAE: 17709.19373394692
4 - MAE: 15563.235198675247
5 - MAE: 18569.139198068155


In [44]:
preds= (preds1+ preds2+ preds3)/3

# Evaluate the model
score = mean_absolute_error(y_valid, preds)
print('MAE:', score)

MAE: 16685.238929407464


In [74]:
preds_test1 = my_pipeline1.predict(X_test)
preds_test2 = my_pipeline2.predict(X_test)
preds_test3 = xgpipe.predict(X_test)
preds_test4 = grad_pipe.predict(X_test)
preds_test5 = grad_pipe1.predict(X_test)
preds_test = (preds_test1+preds_test2+ preds_test3+ preds_test4 + preds_test5  )/5

In [75]:
preds_test

array([125013.861952  , 156481.25804778, 185422.95467041, ...,
       163212.28658423, 112116.3019124 , 227479.68695767])

In [78]:
# Save test predictions to file
output = pd.DataFrame({'Id': X_test.index,
                       'SalePrice': preds_test})
output.to_csv('submission3.csv', index=False) 